In [105]:
import numpy as np

# Create a 5x5x array with random values
X = np.random.random((5,5))
#caluclates the mean of the x array
mean = X.mean()
#calculates the  standard deciation of the x array
sd = X.std()
# the given formula to normalized the array
Z = (X-mean)/(sd)

#displays, original array, meand,standard deviation and the normalized x array
print("Random 5x5 ndarray:\n", X)
print("Mean:",mean)
print("Standard Deviation:",sd)

print("Normalized: \n",Z)

np.save("X_Normalized.npy",Z)

Random 5x5 ndarray:
 [[0.56057177 0.47605182 0.33665041 0.39695151 0.57680673]
 [0.51282501 0.11724067 0.49042328 0.14143757 0.86719809]
 [0.72932188 0.87013619 0.39081343 0.36850863 0.20229294]
 [0.20561544 0.80096492 0.04268025 0.43940503 0.98713299]
 [0.45313757 0.13154    0.05055266 0.01904859 0.94024907]]
Mean: 0.4443022581788073
Standard Deviation: 0.28843923378094133
Normalized: 
 [[ 0.4030988   0.11007367 -0.37322193 -0.16416196  0.45938437]
 [ 0.23756392 -1.13390119  0.15989856 -1.05001212  1.46615226]
 [ 0.98814444  1.47633847 -0.18544229 -0.26277155 -0.83903052]
 [-0.82751162  1.23652616 -1.39239729 -0.01697837  1.88195871]
 [ 0.03063145 -1.08432633 -1.36510418 -1.4743267   1.71941524]]


In [109]:
import numpy as np
#create an array of integers 1 to 100
x = np.arange(0,101)

#squares the first 100 positive array
y=x*x

#Boolean Indexing  to seleect elemnts that are only divisible by 3
z = y[y%3==0]
#prints the original squared arrays
print("Orinigal Array\n",y)
#prints the elemnt that are divisible by 3
print("Elements that are divisible by 3\n",z)

np.save("div_by_3.npy",z)

Orinigal Array
 [    0     1     4     9    16    25    36    49    64    81   100   121
   144   169   196   225   256   289   324   361   400   441   484   529
   576   625   676   729   784   841   900   961  1024  1089  1156  1225
  1296  1369  1444  1521  1600  1681  1764  1849  1936  2025  2116  2209
  2304  2401  2500  2601  2704  2809  2916  3025  3136  3249  3364  3481
  3600  3721  3844  3969  4096  4225  4356  4489  4624  4761  4900  5041
  5184  5329  5476  5625  5776  5929  6084  6241  6400  6561  6724  6889
  7056  7225  7396  7569  7744  7921  8100  8281  8464  8649  8836  9025
  9216  9409  9604  9801 10000]
Elements that are divisible by 3
 [   0    9   36   81  144  225  324  441  576  729  900 1089 1296 1521
 1764 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561
 7056 7569 8100 8649 9216 9801]
